pipeline {

  agent any
  stages {

    stage('Build SUT') {
      steps {
        sh 'cd code/template/testman'
        withMaven(maven: 'MVN3', jdk: 'JDK8') {
          sh 'mvn clean package'
        }
        sh 'cd ../..'
      }
    }

    stage('camp generate') {
      steps {
        sh 'camp generate -d .'
      }
    }
    stage('camp realize') {
      steps {
        sh 'camp realize -d .'
        zip zipFile: 'conf.zip', archive: true, dir: 'out'
      }
    }
    stage('camp execute') {
      steps {
        sh 'camp execute -d .'
      }
    }
  }
}