pipeline {

  agent any
  stages {

    stage('Build SUT') {
      steps {
        withMaven(maven: 'MVN3', jdk: 'JDK8') {
          sh '''cd code/template/testman
          mvn clean package
          cd ../..'''
        }
      }
    }

    stage('camp generate') {
      steps {
        sh ''' cd code
        camp generate -d .'''
      }
    }
    stage('camp realize') {
      steps {
        sh ''' cd code
        camp realize -d .'''
        zip zipFile: 'conf.zip', archive: true, dir: 'code/out'
      }
    }
    stage('camp execute') {
      steps {
        sh ''' cd code
        camp execute -d .'''
      }
    }
    stage('Publish reports') {
      steps {
        step([$class: 'ArtifactArchiver', artifacts: '**/out/*'])
      }      
    }
  }
}