pipeline {

  agent any
  stages {

    stage('Build SUT') {
      steps {
        withMaven(maven: 'MVN3', jdk: 'JDK8') {
          sh '''cd code/camp-perf-test/template/testman
          mvn clean package'''
        }
      }
    }

    stage('camp generate') {
      steps {
        sh ''' cd code/camp-perf-test
        camp generate -d .'''
      }
    }
    stage('camp realize') {
      steps {
        sh ''' cd code/camp-perf-test
        camp realize -d .'''
        zip zipFile: 'conf.zip', archive: true, dir: 'code/camp-perf-test/out'
      }
    }
    stage('camp execute') {
      steps {
        sh ''' cd code/camp-perf-test
        camp execute -d .'''
      }
    }
    stage('Publish reports') {
      steps {
          publishHtml target: [
            allowMissing: false,
            alwaysLinkToLastBuild: false,
            keepAll: true, 
            reportDir: 'code/camp-perf-test/out/config_1/test-reports',
            report files: 'index.html', 
            reportName: 'config_1'
          ]
      }      
    }
  }
}