pipeline {

  agent any
  stages {

    stage('Build SUT') {
      steps {
        withMaven(maven: 'MVN3', jdk: 'JDK8') {
          sh '''cd code/camp-perf-test/template/testman
          mvn clean package'''
        }
      }
    }

    stage('camp generate') {
      steps {
        sh ''' cd code/camp-perf-test
        camp generate -d .'''
      }
    }
    stage('camp realize') {
      steps {
        sh ''' cd code/camp-perf-test
        camp realize -d .'''
        zip zipFile: 'conf.zip', archive: true, dir: 'code/camp-perf-test/out'
      }
    }
    stage('camp execute') {
      steps {
        sh ''' cd code/camp-perf-test
        camp execute -d .'''
      }
    }
    stage('Publish reports') {
      steps {
        step([$class: 'ArtifactArchiver', artifacts: '**/statistics.json'])
      }      
    }
  }
}